CREATE TABLE users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name varchar(100) NOT NULL,
    last_name varchar(100) NOT NULL,
    email_address varchar(1000) NOT NULL UNIQUE,
    mobile_number varchar(1000) NOT NULL UNIQUE,
    password varchar(200) NOT NULL,
    created timestamp with time zone NOT NULL DEFAULT NOW(), 
    created_by varchar(100) NOT NULL DEFAULT 'admin',
    last_modified timestamp with time zone NOT NULL DEFAULT NOW(), 
    last_modified_by varchar(100) NOT NULL DEFAULT 'admin',
    version bigint NOT NULL DEFAULT 0
    );